2.3. add basic registration page
mir-org/eCommerce-Application pull request #9
Opened 2023-08-16 20:02 UTC by miroslav-zarenkov

## PR Type

What kind of change does this PR introduce?

```
- [x] Feature
- [ ] Bugfix
- [ ] Refactoring
- [ ] Documentation changes
- [ ] Tests
- [ ] Other
```

## What's new?

Added basic layout of registration page.

2023-08-17 12:17 UTC, Margaryta-Maletz reviewed
Looks good for me)

2023-08-17 12:17 UTC, Margaryta-Maletz commented on src/app/view/main/registration/registration-view.ts
> +import { SIGN_UP_CLASSES, SIGN_UP_TEXT, SIGN_UP_KEY } from '../../../enums/enums';
try to use aliases instead ../../../enums/enums

2023-08-17 12:17 UTC, Margaryta-Maletz commented on src/app/view/main/registration/registration-view.ts
> +  // eslint-disable-next-line max-lines-per-function
Wow... better change max-lines in eslint
And again, add TODO and do not forget about comments

2023-08-17 12:37 UTC, GinezisNWD requested changes
Я думаю что не стоит уносить константы так далеко, ты или положи прям в файл, или файл с константами положи  рядом с файлом в папку registration.

2023-08-17 12:54 UTC, GinezisNWD requested changes
нужен рефактор, обсудим на созвоне.

2023-08-17 12:54 UTC, GinezisNWD commented on src/app/view/main/registration/registration-view.ts
> +    submitBtn.getElement().setAttribute('type', 'submit');
просто говорю что при нажатии на кнопку с typе submit, вся страница будет перезагружаться, это нужно убрать, ну или делать prevent default.

2023-08-17 12:54 UTC, GinezisNWD commented on src/app/view/main/registration/registration-view.ts
> +    this.viewElementCreator.addInnerElement(this.form);
я всё это можно вынести в метод  "условно" configForm , и добавление кнопки в тот же метод.

2023-08-17 12:56 UTC, GinezisNWD commented on src/app/view/main/registration/registration-view.ts
> +import { SIGN_UP_CLASSES, SIGN_UP_TEXT, SIGN_UP_KEY } from '../../../enums/enums';
в моем понимании эта штука должна лежать или в файле рядом, или прям в самом файле, и элиасы не нужны будут.

2023-08-19 21:49 UTC, pyropetrick approved these changes

2023-08-19 21:49 UTC, pyropetrick commented on src/app/view/main/registration/registration-view.ts
> +import { MyCustomerDraft } from '../../../../api/CustomerAPI/customer-api-type';
maybe set up aliases for imports

2023-08-21 23:16 UTC, GinezisNWD approved these changes
ты настолько красавчик, что можешь бить женщин и детей.

2023-08-21 23:17 UTC, toronto-tokyo approved these changes

2023-08-21 23:26 UTC, merged